name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1  # actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        ACTIONS_DEPLOY_KEY: ${{secrets.key}}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: docs
